### ISSUE TITLE
Crashes with 04-30-07

### ISSUE THREAD

**Issue by Chronial** [Wulf2k/DaS-PC-MPChan#10]
Activating DSCM-Net causes my dark souls to crash in irregular intervals. Here's a dump from one of these crashes. [DARKSOULS-mini.zip](https://github.com/Wulf2k/DaS-PC-MPChan/files/244205/DARKSOULS-mini.zip)

I assume that it's just the normal dscm connection attempt that causes the crash, since the irc feature causes that code to be called a lot more.

**Comment by Wulf2k** [comment]
Weird, i haven't experienced a crash for several versions now, and i left
it running for a couple hours yesterday.

I'll take a look at it later tonight.

On May 1, 2016 11:22, "Chronial" <notifications@github.com> wrote:
>
> Activating DSCM-Net causes my dark souls to crash in irregular intervals.
Here's a dump from one of these crashes. DARKSOULS-mini.zip
>
> I assume that it's just the normal dscm connection attempt that causes
the crash, since the irc feature causes that code to be called a lot more.

**Comment by Chronial** [comment]
I added some logging to see whether the game crashed when dscm tried to initiate a connection. That is not the case, but I discovered #13. In fact, as 40 connections where initiated at startup the nodecode went to 20 instantly and never came back down, so dscm never initated another connection after startup.

#13 might actually be the cause of this bug – maybe the connection storm that dscm causes on startup gets something into an invalid state, which triggers this crash later on. My most recent crash came in the exact moment I pressed "summon phantom" on a summoning sign.

**Comment by Wulf2k** [comment]
Just to be sure, are you running PVP watchdog?

Have you ruled out the namecrash?

**Comment by Chronial** [comment]
nope, only dscm and dsfix.

**Comment by Wulf2k** [comment]
Install watchdog and see if the crashes go away.

Players with names over 15 characters will crash you without it.

**Comment by Chronial** [comment]
Ah, didn't know about the namecrash. I am again and again surprised by the shittiness of that port ^^. Installed PVP watchdog and will report back :). Can't play as much during the week though.

**Comment by Chronial** [comment]
Installed PVP watchdog, but also #16. Crashes are gone now, so closing this.
