### ISSUE TITLE
DSCM adding self as node?

### ISSUE THREAD

**Issue by Wulf2k** [Wulf2k/DaS-PC-MPChan#100]
from Skraelos sent 5 days ago

Hey there!

DSCM Steam64: 01100001025bd3cc

My profile: http://steamcommunity.com/id/skraelos

Hope that helps. It's also worth noting that this situation doesn't always happen; but I do encounter it every, like, 4-5th time I relaunch the game and DSCM.

[–]to Skraelos sent 3 days ago

Whenever it happens again next, look in the Active Nodes list.

Does it show you in there twice?

If so, does it somehow list you with two different Steam IDs?

[–]from Skraelos sent 2 days ago

It happened just now. I was gravelording in Burg and Parish on ng+, it was fine; just came to darkroot, relaunched the game to get back to 0 nodes and populate myself with darkroot nodes a bit faster (I always do that when I come to new zones, the node replacement auto-system doesn't really make haste to remove the nodes from previous zones...), waited for ~18 nodes and used the death eye. Right at that moment the gravelord sign appeared beneath my feet and now moves together with me.

And no, I only see one instance of myself in active nodes, and steam id seems to be correct. Weird stuff...

**Comment by Chronial** [comment]
DSCM will never try to connect you to yourself. I don't think that this is related to DSCM.
https://github.com/Wulf2k/DaS-PC-MPChan/blob/d1cb4b797215838a2a32a351c4e1d4bb32f03fe4/DaS-PC-MPChan/MainWindow.vb#L382

**Comment by Wulf2k** [comment]
Yeah, I know it shouldn't but I've never heard a single instance of the regular game adding the local player as a node.

When I have time, I should confirm that kindling a bonfire lets you give yourself a free health refill if you're added as your own node....
