### ISSUE TITLE
Outdated readme on wulf2k.ca

### ISSUE THREAD

**Issue by Chronial** [Wulf2k/DaS-PC-MPChan#101]
The easiest would probably to use this link instead: https://github.com/Wulf2k/DaS-PC-MPChan/blob/master/Readme.md
Or if you really dislike having the github interface, you can also use this link: https://raw.githubusercontent.com/Wulf2k/DaS-PC-MPChan/master/Readme.md. No nice formatting, but still better than an outdated readme with no nice formatting ^^.

**Comment by Wulf2k** [comment]
I'll update that to point to the github version this weekend.

**Comment by Wulf2k** [comment]
Website should now point to the Github readme.
