### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by Wulf2k** [Wulf2k/DaS-PC-MPChan#103]
from cheezbuggah sent 1 day ago

Hello! First off, thank you for taking the time to develop dscm. Unfortunately, I've encountered a bug that, after two days of searching, I can't seem to find a solution to.

Specifically, when I launch the dscm (both the test verson and the normal version), I get the following error: "The remote server returned an error: (403) forbidden". My first hunch was an outdated version of .NET framework, yet I've downloaded all 4.5 updates + the 4.6 update, and each time I attempted an installation it told me my a more recent version of .NET is already installed on this machine. I have also added an exception in my antivirus program, yet the error still persists.

I hope I'm not troubling you too much with this.

**Comment by Wulf2k** [comment]
from cheezbuggah sent 1 day ago

The testing version. It would start and give me the error, and then dscm would just stay blank and not give me any nodes. I just downloaded the stable version, and that one does work, even after giving me the error. So I guess it's fixed for me? Is it extremely necessary to use the testing version?

**Comment by Wulf2k** [comment]
from cheezbuggah sent 1 day ago

http://dscm.wulf2k.ca gives me the "It works!" page. Your website opens normally as well.

**Comment by Chronial** [comment]
I would guess this is a proxy issue. I think we use the proxy settings from IE.

**Comment by Chronial** [comment]
This is probably the same as #107. Ask him if he can open http://chronial.de/scripts/dscm/is_online.php?ids=76561197960435530,76561198003675286.

**Comment by Wulf2k** [comment]
Not the original guy, but one guy that was getting the 403 error fixed it by wiping his machine.

So, that's a perfectly reasonable thing we can suggest to anybody experiencing issues.

**Comment by Chronial** [comment]
I see three things that could cause this:

* Proxy
* Antivirus
* Virus

It's always amusing how the symptoms of having AV are 90% the same as having a Virus :smiley:

**Comment by Wulf2k** [comment]
I usually find viruses to run more efficiently and be less obtrusive than anti-virus.
