### ISSUE TITLE
Catch "Access Denied" exception

### ISSUE THREAD

**Issue by Wulf2k** [Wulf2k/DaS-PC-MPChan#109]
If Dark Souls is run as admin but DSCM is not, there is an unhandled exception.

**Comment by Chronial** [comment]
Fyi, I did not make any change here recently. The last change that could have affected this, is here:
https://github.com/Wulf2k/DaS-PC-MPChan/commit/be2347e822c089bff9fd4bb512a03ad9d3a21028#diff-1077b06ccf265332b8a199824faad952R105

What exactly is the error that people are reporting? A crash popup?

**Comment by Chronial** [comment]
Thanks to the commit tagging, you can also see that this was included in the 05-12 release:
![tags](http://chronial.de/misc/screenshots/firefox_2016-06-18_15-32-35.png)
