### ISSUE TITLE
Latest Testing Version, Error Loading Nodes List

### ISSUE THREAD

**Issue by Vicadin777** [Wulf2k/DaS-PC-MPChan#117]
Was working fine till yesterday, now it gives an error connecting. Error loading node list: An error occurred while sending the request.

Internet is working, checked firewall too. An older version seems to work fine.

Edit: Seems to work after leaving it alone for a few minutes.
Edit Edit: Problem still persists. Unchecking and rechecking join dscm results in the same error.

**Comment by Chronial** [comment]
@Vicadin777 Are you still having this problem?
