### ISSUE TITLE
Nodes with weird world IDs

### ISSUE THREAD

**Issue by sometoby** [Wulf2k/DaS-PC-MPChan#118]
I keep getting error notifications from my dscmstat.us app because it runs into nodes that have world IDs it can't map to a name. Here's a list of IDs it has error'd over so far:
- 11-1
- 11-2
- 12-2
- 14--1
- 14-2
- 15--1
- 16--1
- 17-1
- 17-2
- 19-1

None of these IDs are listed in DSNode.vb. Beats me where they are coming from. Have you got any ideas?

**Comment by Chronial** [comment]
These are actually two numbers `A-B`. If the string ends in `--1` (e.g. `14--1`), that means the second number is `-1`. The easiest way to find out what these numbers mean is to contact the players via steam (you have their steamid ;). And ask them where they are / where they where 2 minutes ago.

I once identified one of these as being inside the MP fighting arena in oolacile. I think it was `12-2`, but not sure :).
