### ISSUE TITLE
Update documentation on non-steam versions of Dark Souls

### ISSUE THREAD

**Issue by Kilovice** [Wulf2k/DaS-PC-MPChan#123]
As no one (that I have seen) has asked or made any comment regard the fact that Dark Souls could have been purchased on disk, how would DSCM act without a Steam64?

**Comment by Wulf2k** [comment]
DSCM will only work with the latest version of Dark Souls, which has Steam-based matchmaking.

GFWL-matchmaking for Dark Souls was shut down a few versions ago.
