### ISSUE TITLE
IRC connection logic is broken

### ISSUE THREAD

**Issue by Chronial** [Wulf2k/DaS-PC-MPChan#13]
This code does not what it should:
https://github.com/Wulf2k/DaS-PC-MPChan/blob/ebedbbcd0a93648649f9b22dcfd21ab070b21990/DaS-PC-MPChan/DSCM.vb#L533
```VB
'Autoconnect to any nodes when Currnodes are under 4
If Val(txtCurrNodes.Text) < 4 Then
     attemptConnSteamID(tmpSteamID)
```

The problem is that connecting to nodes takes some time, so `txtCurrNodes` is actually a number from the past. The result is that for a few seconds, a new connection is initiated every 200 ms (`refTimer` interval). In my test, dscm initiated 40 connections after I activated dscm-net.

**Comment by Wulf2k** [comment]
I was aware of the issue but didn't think it would get that bad this
quickly.  I'll build a connection queue tomorrow some time.
