### ISSUE TITLE
[Suggestion] Report non-dscm nodes to irc

### ISSUE THREAD

**Issue by Chronial** [Wulf2k/DaS-PC-MPChan#14]
The client could report all nodes it knows about to IRC, which should massively increase the number of nodes available in IRC. I think it's safe to assume that it will always be only a small fraction of the Dark Souls playerbase that runs DSCM.

Advantages:
* Bigger player pool will allow DSCM to choose "better" nodes (same world + coop range)

Disadvantages:
* We can only report data that we get from steam for these nodes, maybe limiting interesting matchmaking ideas.

The disadvantage is not too extreme though, as we can still report more data for "ourselves". Then we have just some nodes with more, some nodes with less data.

**Comment by Wulf2k** [comment]
Reporting of active nodes to IRC should be in.
