### ISSUE TITLE
Windows Defender detected Trojan:Win32/Wacatac.B!ml in DSCM

### ISSUE THREAD

**Issue by Gigaluuri** [Wulf2k/DaS-PC-MPChan#144]
I don't know if this is a false positive, but Windows detected something called Trojan:Win32/Wacatac.B!ml in DSCM and deleted the executable. I haven't found any other posts anywhere about this in particular, so I'll post this here now. 
I downloaded DSCM as a part of InfernoPlus' new multiplayer fix mod called Dark Souls: Remastest, not from Nexus or here. 
So far only the DSCM executable had it, but I'm scanning for potential hidden stuff.

**Comment by Wulf2k** [comment]
I can't vouch for EXEs in any packs that I didn't put together, so I am *not* stating that copy is safe, however, false positives used to be very common when I first started releasing.  I haven't heard about it for a while, but any time you're using one program to modify the memory of another, that's going to trigger some interest from AV programs.

That being said, the official source code is available for viewing here, and I do vouch for my code.  If somebody has slipped a virus into a compiled version of my exe and put it up for download somewhere else, that's not something I can deal with as a Github issue.
