### ISSUE TITLE
Weird IRC Server behaviour

### ISSUE THREAD

**Issue by Chronial** [Wulf2k/DaS-PC-MPChan#17]
Might there be something wrong with the IRC Server, or is that intended behavior:

I logged in with my IRC client to have a look and noticed, that I receive updates quite irregularly, and in massive blocks. The intervals between the updates range from 10 seconds to over a minute.

**Comment by Wulf2k** [comment]
It's actually an issue with my threading code on the clients.

They all get hung up on the read from the server, so they won't report
until they get some input to move past it.  I assumed the ping on the
server would be randomly timed among the clients, causing enough
communication to make it work close enough to how it should until i found
time to fix it.

Instead they all appear to have synced up.

**Comment by Wulf2k** [comment]
I'll test this tonight before closing it but this should be fixed in your latest addition, right?

**Comment by Chronial** [comment]
Yes, #21 should have fixed this.
