### ISSUE TITLE
Unable to play behind NAT

### ISSUE THREAD

**Issue by sgtsquiggs** [Wulf2k/DaS-PC-MPChan#18]
First, thank you for this mod. Without it, multiplayer was plainly not working for us.

Now our problem:

Able to connect to DSCM, seeing a ton of nodes. See messages all over the world. Cannot connect to another player who is behind the same NAT as I am. We have been playing together this way for a month using your mod without issue, but it stopped working yesterday. We've tried using the stable version and the testing version but no luck. We are level 75 and 81, one of us has cleared New Londo Ruins, the other has not. Player who has no completed is human looking for the other players' sign. DCSM say's we're connected, but no sign.

Not sure what's up :(

**Comment by Wulf2k** [comment]
Drain the water.  No summoning until that water is drained.

**Comment by sgtsquiggs** [comment]
Doh. Thanks.
