### ISSUE TITLE
Update info not visible by default

### ISSUE THREAD

**Issue by Chronial** [Wulf2k/DaS-PC-MPChan#24]
I sneakily changed the default state of dscm to expanded in #21. I would argue that that makes a lot more sense. Maybe it would even be a good idea to remove the non-expanded state – or what exactly is the usecase for that?

A side effect of that is that the update info is not visible anymore when you open the program, which is obviously not good :).

**Comment by Wulf2k** [comment]
Some people have said they still use it.  I haven't removed it because it's linked to the hook for the data dumping, and there are still a few rare instances where that won't work for people.  It will still attach and read data, but the code insertions always fail.

**Comment by Chronial** [comment]
>  It's linked to the hook for the data dumping
Not anymore :). I removed that link, partially because that was incompatible with the DCSM-Net. As you didn't load nodes without extended view, you weren't an active part of DCSM-Net.

I would leave that as it is for now, and see whether the dump-hook is still causing problem for people. If it is, we can add option to disable just that.
