### ISSUE TITLE
Enable DSCM-Net on startup?

### ISSUE THREAD

**Issue by Chronial** [Wulf2k/DaS-PC-MPChan#25]
Is there a specific reason why you set the dcsm-net to disabled by default? As we want the maximum possible amount of data, I would say it makes more sense to enable it by default?

**Comment by Wulf2k** [comment]
It's easier to sort out the cause of errors when a crash happens immediately after a click.  If everything's automatic, nobody knows.

**Comment by Chronial** [comment]
Good point, so we should wait with this till the feature is more stable.

**Comment by Wulf2k** [comment]
I've pushed it out as a testing release, but won't overwrite the stable release for a bit.

**Comment by Wulf2k** [comment]
I think for the next release I'll tie expand/join into registry values that get checked on startup.

And I apparently forgot to commit it, but I set the update label to be visible in both modes and tweaked its position slightly.

What do you think about setting the column widths to auto-adjust?  No reason not to, right?

**Comment by Chronial** [comment]
> What do you think about setting the column widths to auto-adjust? No reason not to, right?

I don't know – I don't quite see the benefit: The text is fixed width and for all but the name column we know which text is going to be displayed, so the standard column size should always be correct, right?
Maybe just adapt the width of the name column?

**Comment by Wulf2k** [comment]
I suppose.  I was mostly just thinking of the easiest way not to have the horizontal scrollbar appear when the vertical scrollbar appeared, and shaving those few pixels off each column was the easiest way that came to mind without manually changing the column widths.

**Comment by Chronial** [comment]
Ah, I was wondering why there is a horizontal scrollbar :). But adjusting the name column width would perfectly solve that, right?

**Comment by Wulf2k** [comment]
I'd imagine so.

**Comment by Chronial** [comment]
Dcsm-net enabled in #37.
