### ISSUE TITLE
Remove steamIds and manual connect from DSCM-Net

### ISSUE THREAD

**Issue by Chronial** [Wulf2k/DaS-PC-MPChan#28]
I think we should remove the manual connect functionality from DSCM-Net. Maybe also the steamIds, so you can't just type them in.

IMHO this feature clearly goes against the spirit of Dark Souls and also makes undesirable behavior easier. And I can't see any good use for it anyways.

Maybe not yet, but once we feel the irc autoconnect is good and stable.

**Comment by Wulf2k** [comment]
I think I'd rather have a fully controllable  blacklist in than to remove the idea of manual node connections.

All of this automatic connection stuff is secondary to the mod's original goal of being able to pick a friend, sit down, and just play together without screwing around with placing and removing summoning signs for half an hour.

If I can be satisfied enough with the automatic pairing that two or three friends can always start up the game and be playing together within 5 minutes, then I'd be open to its removal.  Until then I think that stream sniping and all the other inconveniences are just something that are bound to happen.

Besides, anybody that wants to can just keep a copy of the current version of DSCM around and force a connection anyway.

**Comment by Wulf2k** [comment]
Hiding the current SteamIDs is probably fine.

**Comment by Chronial** [comment]
Ah, nono, you missed my point :). I was only talking about the IRC Part. Remove the steamId column in *only* that list, and remove the double-click functionality from that list.

**Comment by Wulf2k** [comment]
Ah, k.  I'm much more open to that idea but not 100% convinced the automatching is good enough.

Maybe if we added some checkable criteria in the space freed by the SteamID removal?  Or a pulldown for preferred MP type?

If somebody's looking for darkwraith invasions, only auto-add humans with the right level range?  Co-op, humans with that level range.  Darkmoons, only autoadd those with sin or in dark anor londo, with that third level range?

Speaking of darkmoons, I want to add Indictments to the reporting line along with the proper level event flags once I track them down.

**Comment by Chronial** [comment]
> Ah, k. I'm much more open to that idea but not 100% convinced the automatching is good enough.

I agree, this is more a reminder for the future.

> Maybe if we added some checkable criteria in the space freed by the SteamID removal? Or a pulldown for preferred MP type?

I would prefer to use the player's covenant (isn't that actually their point?) instead of a pulldown. And that is actually on my todo list, I'm just waiting for you to dig the covenant information out of the game ;).

**Comment by Wulf2k** [comment]
>  I'm just waiting for you to dig the covenant information out of the game ;).


	Dim tmpptr = ReadInt32(dsBase + &HF78700)
	tmpptr = ReadInt32(tmpptr + 8)
	
	Dim selfIndictments = ReadInt32(tmpptr + &HEC)
	Dim selfCovenant = ReadInt8(tmpptr + &H10B)
	
0	None	
1	Way of White
2	Princess's Guard
3	Warrior of Sunlight
4	Darkwraith
5	Path of the Dragon
6	Gravelord Servant
7	Forest Hunter
8	Darkmoon Blade
9	Chaos Servant


The above needs confirmation as it's just copied straight from my notes and I haven't confirmed it recently.

I do rarely have mistakes in my notes.

**Comment by Wulf2k** [comment]
And yeah, basing it off of their covenant is the better way to go.

**Comment by Wulf2k** [comment]
And with the covenant checks, we should also care about which ring is worn.

If that's something you're actively working on, maybe just work a dummy value into the check that can indicate the ring.  If you're a forest hunter without the ring on, you probably don't care about matching with people in the forest.

I'd also like to work in a tab that people can check to see if they're currently capable of hosting.  So it would check if they're human, list the SL ranges that can invade them from the various methods, show if their bosses are dead, and show any level-specific criteria that need to be met.

Failing to drain the water in the ruins is probably the most common issue for people that can't connect and everything else looks right.

Do you think I'm starting to put in too much, or can you think of a pretty way to display that information?

**Comment by Chronial** [comment]
I think ringdata is:
```
Dim tmpptr = ReadInt32(dsBase + &HF78700)
Dim heroBPtr = ReadInt32(tmpptr + 8)

Dim selfIndictments = ReadInt32(heroBPtr+ &HEC) 
Dim selfCovenant = ReadInt8(heroBPtr+ &H10B)
Dim ring1type = ReadInt32(heroBPtr + &H280)
Dim ring2type = ReadInt32(heroBPtr + &H284)
```

ringtype of cat covenant ring is `103`

Displaying summoning ability seems like a very ambitious project :)

**Comment by Wulf2k** [comment]
That's in the right range.

Helmet is 268 or 26c i believe, so that would fit right in with the rings.

**Comment by gpotter2** [comment]
> I think we should remove the manual connect functionality from DSCM-Net. Maybe also the steamIds, so you can't just type them in.

Question: then how do you play with your friends ? what if the nodes are full ?

**Comment by Wulf2k** [comment]
If you re-read, he clarifies that he just means manually connecting to the huge list of players in DSCM-Net, not manually connecting to friends that you know personally.

**Comment by gpotter2** [comment]
Ok :)

**Comment by Chronial** [comment]
I think somewhere along the way, we already removed the steam IDs due to space restrictions. The manual connection is still possible via double-click, but I think that's obscure enough to not actually affect the player base at large.
