### ISSUE TITLE
Error processing player report

### ISSUE THREAD

**Issue by Master-chan** [Wulf2k/DaS-PC-MPChan#40]
There is "Error processing player report - Индекс находился вне границ массива." message on the bottom of DSCM-Net list, which I believe translates into "array out of bounds".
Overall software seems to be working fine. I'm using 2016.05.06.01 version.

**Comment by Chronial** [comment]
@Master-chan  don't worry that message does not signal an actual problem ^^.

@Wulf2k should we maybe remove these messages? If one client gets these failures, all clients get them, so we can just check them locally. And I'm sure this will only confuse people.

**Comment by Wulf2k** [comment]
Yeah, I'd say they're no longer useful to the general public.

**Comment by Chronial** [comment]
Has been removed in 5606caf07. I think this can be closed.
