### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by Wulf2k** [Wulf2k/DaS-PC-MPChan#42]
Current master can't seem to find the readme on launch if it's an EXE outside of the build folder.

**Comment by Wulf2k** [comment]
It's not the readme, it complains about CommonMark.

System.IO.FileNotFoundException: Could not load file or assembly 'CommonMark, Version=0.1.0.0, Culture=neutral, PublicKeyToken=001ef8810438905d' or one of its dependencies. The system cannot find the file specified.
File name: 'CommonMark, Version=0.1.0.0, Culture=neutral, PublicKeyToken=001ef8810438905d'
   at DSCM.DSCM.loadReadme()
   at DSCM.DSCM.DSCM_Load(Object sender, EventArgs e)

**Comment by Wulf2k** [comment]
It works if I copy the CommonMark.dll with it, but I'd prefer not to do this.

**Comment by Wulf2k** [comment]
Removed CommonMark, help tab is now a textbox.

**Comment by Chronial** [comment]
I think [ILMerge](https://www.microsoft.com/en-us/download/details.aspx?id=17630) might solve that issue. I'm busy right now, will have a look later.
