### ISSUE TITLE
Sorting in DSCM-Net

### ISSUE THREAD

**Issue by Chronial** [Wulf2k/DaS-PC-MPChan#45]
The sorting in DSCM-Net is suboptimal:

* The sin column sorts lexicographically instead of by integer value
* New nodes should automatically be sorted.

**Comment by hydra-chan** [comment]
It would also be nice if there was some sort of radix sort on the different fields in the order the user decides. (Well, I don't know for certain if "radix sort" is the correct term, but I mean specifically sorting the nodes such that they sort by multiple keys in an order.)

I imagine it would be easy enough to have a text box that parses a set of non-duplicating characters, with certain chars mapped to certain keys. Ex. "nml" would mean "sort by name, then MP Zone, then Soul Level." If the input isn't correct in anyway, keep it simple and throw an angry message.

**Comment by Chronial** [comment]
This feature is already implemented – for "nml", just click the soul level, then the zone, then the name column. This is btw. how sorting works everywhere – you can try that for example in windows explorer.

**Comment by hydra-chan** [comment]
Is that feature in the test build or just on Github? I don't observe this in the testing release.

**Comment by Chronial** [comment]
That has always been working in every tab.

**Comment by Wulf2k** [comment]
Nope.

For me, it only sorts by a single column.  If I sort by PhantomType and then SL, it will only sort by SL.

**Comment by Chronial** [comment]
Did you try sorting by SL and then by phantomtype?

**Comment by Wulf2k** [comment]
Huh, you're right.

Neat.
