### ISSUE TITLE
Detected as virus

### ISSUE THREAD

**Issue by Chronial** [Wulf2k/DaS-PC-MPChan#46]
Can we do something about this getting detected as a virus?
You should probably upload the file to virus total before you do a release Here is the report for the last testing release:
https://virustotal.com/en/file/3fb9a3a068b2e91d5f9a23e67438fb6e0f107d6430cb94c63fb57c6612bf1e49/analysis/1462881420/

I think that's actually alright. But people on the reddit have reported more positives, so I'm not sure.

Maybe the AV tools detecting based on heuristic and sending the file to a server for closer inspection, where it is cleared?

**Comment by Chronial** [comment]
For testing I made new release build and submitted that. That's a different situation: https://virustotal.com/en/file/4efc4093f3419a001e6ee6966ff168b99a35a9032d4b5d3300eafaf5b5fe3ddf/analysis/1462883053/

It got detected by 11 tools, including bigger ones. If this doesn't improve, we really should see whether we can do something about this.

**Comment by Chronial** [comment]
It looks like you should digitally sign the releases
http://programmers.stackexchange.com/questions/191003/how-to-prevent-my-executable-being-treated-from-av-like-bad-or-virus

**Comment by Chronial** [comment]
https://msdn.microsoft.com/en-us/library/xc31ft41%28v=vs.110%29.aspx

**Comment by Wulf2k** [comment]
I'll see what I can do about this the next time I'm about to make a release.

I don't think signing it alone will be enough to keep it from flagging though.  That 2nd last link just talks about it getting flagged because it's not popular.  That's different than being flagged because the AV detects that it tries to inject code into other processes.

Still, it can't hurt, and maybe some of the AVs can ignore based on my signature.

**Comment by Chronial** [comment]
I think this is about reputation. The AVs collect the number of people that have used your binary and not flagged it as a virus. That influences the heuristic.

If you don't sign your binaries, the reputation is per binary, if you sign them it is per signature. This way you can actually build a reputation and not have every new release flagged as a virus in the beginning.

**Comment by Chronial** [comment]
Looking at this some more, I don't think strong name signing is the right kind of signature for this. I think you need this kind: https://blog.didierstevens.com/2008/12/31/howto-add-a-digital-signature-to-executables/
But that requires a certificate from a root CA and that costs money :(.

But strong name signing would still be useful for the autoupdater, especially since you don't use https for your website. But the last testing release you made was not strong name signed. You can have look here for how to check if your assembly is signed: https://blog.codingoutloud.com/2010/03/13/three-ways-to-tell-whether-an-assembly-dl-is-strong-named/ (this also has some information about the two different signing methods).

**Comment by Wulf2k** [comment]
I'll try to figure out the signing more for the next release, after this weekend.

**Comment by Chronial** [comment]
There's no rush here. You can just do the next release without signing and we will worry about that later.

**Comment by Wulf2k** [comment]
I haven't received any reports of AV issues since I started signing the EXE.
