### ISSUE TITLE
MaxNodes reading is broken

### ISSUE THREAD

**Issue by Chronial** [Wulf2k/DaS-PC-MPChan#57]
I don't thin the MaxNodes reading code is correct. It frequently returns 0 or arbitrarily large numbers (`1297035621`) for me. This is ignored by the frontend and thus hidden from the user. But DSCM-Net uses this as a basis for connect decisions, so that is a serious problem.

**Comment by Wulf2k** [comment]
Is it changing during play, or just during load screens and such?

**Comment by Chronial** [comment]
during play

**Comment by Chronial** [comment]
This is consistently reproducible and just broken. We just never noticed because you hide the error (bad boy :stuck_out_tongue: ).
The readout always works when you start the game. But as time passes, the values are only sometimes there, and after a while it just completely stop working.

**Comment by Wulf2k** [comment]
Well, I must follow a bad pointer somewhere along the line.

I'll see if I can find some time to figure it out tonight.
