### ISSUE TITLE
Measure bandwidth consumed

### ISSUE THREAD

**Issue by Wulf2k** [Wulf2k/DaS-PC-MPChan#59]
I've seen a comment or two about DSCM overloading people's networks.

I don't think it's a serious problem but we should probably measure it some time to see how much does get used.  If necessary we can implement some minor forms of compression on the data with minimal hassle.

**Comment by Chronial** [comment]
We have 1200 Nodes, their info is published every 2 to 3 minutes (let's take 2), A publish takes about 128bytes.

 http://www.wolframalpha.com/input/?i=%281200++*+128+bytes%29+%2F+%282+minutes%29
-> 1.2kb/s. That is not a lot. Monitoring my process gives the same numbers.

I don't think you can easily add compression on top of IRC.

**Comment by Wulf2k** [comment]
It would be relatively simple to pack the reports into a txt file, deflate it, and then uuencode that for transmission through IRC.  The savings probably wouldn't be amazing, but using a larger character set instead of just alphanumeric would give something.

I'm gonna say it's not worth looking into for 1.2 kb/s though.
