### ISSUE TITLE
Consider an auto-update method.

### ISSUE THREAD

**Issue by Wulf2k** [Wulf2k/DaS-PC-MPChan#60]
Not sure of the best way to implement it, but there should probably be a button to just download the latest DSCM from within DSCM.

**Comment by Wulf2k** [comment]
I'm thinking we should just changed the red label to a button that will download and auto-open the latest RAR.

**Comment by Chronial** [comment]
I think it would be a better to idea to stop making the version part of the filename and then to replace the executable with the new version when the button is pressed.

**Comment by Wulf2k** [comment]
I suppose that's just crazy enough to work...

Do you have a good method for a program to replace its own EXE?  Any time I've done it in the past I've created a temporary EXE to pass control to, delete the original EXE and replace it, then pass control back and delete the temporary EXE.

It works, but it's probably not the greatest.

**Comment by Wulf2k** [comment]
Dim filename = Process.GetCurrentProcess.Modules(0).FileName
        File.Move(filename, "test.exe")

That'll work.  Then just download the new EXE in it's place, start that process and end the current one, and have the new process delete "test.exe" from its current folder as part of startup.

**Comment by Chronial** [comment]
Did you test that? I don't think you can move the executable of a running program. I suggest this:
Add two command line switches to DSCM:

* If DSCM is started with `--updated f1`, it will run normally but start a second thread that will try to delete `f1` every second.
* If DSCM is started with `--update f1`, it will not display the UI, but try to delete `f1` every second for 5 seconds. If that fails, it will display an error message about a failed update. If it succeeds, it will move `f2` to `f1` and then start `f1` with `--updated ME`, where `ME` is the name of the current executable. Then it will quit.

Clicking the update button will:

1. download and extract the new version *into the same folder* as the current executable
2. run the new version with `--update ME`
3. Check whether the starting worked and exit

The same folder thing is important to make sure the user actually has write permissions there.

**Comment by Wulf2k** [comment]
My code does work.  It won't "move" it while it's running but it will rename it.

So I think renaming itself to DSCM_old.exe while downloading and launching the new one will work, then just "if exists(dscm_old.exe) then delete" on startup.

That way the old version is still available if the new version fails to run for some reason, and it's silently removed the first time the new one does run.  Saves the hassle of having to care about the "update state" as well.

**Comment by Chronial** [comment]
This is done, #104 is about the missing signature check.
