### ISSUE TITLE
No connection could be made because the target machine actively refused it 

### ISSUE THREAD

**Issue by RodolfoFigueroa** [Wulf2k/DaS-PC-MPChan#64]
Pretty much what the title says. Every time I try to join DSCMNet I get this error, followed by an ip address. I've already given full firewall access to the process and still nothing.

**Edit:** Several other users are having the same error, all with the same ip (50.72.100.113:8123): https://www.reddit.com/r/darksouls/comments/4ilq2x/dscm_dark_souls_connectivity_mod/d36fgrt

**Comment by gpotter2** [comment]
It was corrected, as he said on the page

**Comment by Wulf2k** [comment]
This error should have been fixed yesterday.
