### ISSUE TITLE
[Compile] Could not find *.pcx file

### ISSUE THREAD

**Issue by hydra-chan** [Wulf2k/DaS-PC-MPChan#65]
I noticed in the last commit that we should notify @Wulf2k of any issues. Here is one I guess.

```
1>------ Build started: Project: DSCM, Configuration: Debug Any CPU ------
1>          1 file(s) copied.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2883,5): error MSB3322: Unable to get MD5 checksum for the key file "Wulf2k-DSCM.pfx". Could not find file 'F:\GitHub\DaS-PC-MPChan\DaS-PC-MPChan\Wulf2k-DSCM.pfx'.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

If I disable signing, it seems to compile fine. However, I don't know if there might be any potential consequences of not signing, so I'll leave this here.

Additionally, if I were to release more Darkmoon Edition updates, should I sign it (probably with a separate key I would imagine)? Actually, I've never dealt with signing before, so this is all new to me.

**Comment by Wulf2k** [comment]
Yeah, disable signing.

In hindsight I shouldn't have synced a version with signing enabled, and should have just enabled it myself right before each release.

There's no harm in signing your release with your own key but there's not too much of a benefit.  It may or may not help some antivirus programs build up trust for you, but I can't even tell if that's happening with the main release.

**Comment by hydra-chan** [comment]
Ok, thanks for the response.
