### ISSUE TITLE
Crash in attach [2016-05-19-21]

### ISSUE THREAD

**Issue by Chronial** [Wulf2k/DaS-PC-MPChan#85]
Reported [by DevLink on Reddit](https://www.reddit.com/r/darksouls/comments/4ilq2x/dscm_dark_souls_connectivity_mod/d3h3wzj):
```
************** Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
bei DSCM.DarkSoulsProcess.findDllAddresses()
bei DSCM.DarkSoulsProcess..ctor()
bei DSCM.MainWindow.attachDSProcess()
bei DSCM.MainWindow.Lambda$_R19-5(Object a0, EventArgs a1)
bei System.Windows.Forms.Timer.OnTick(EventArgs e)
bei System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
mscorlib Assembly-Version: 4.0.0.0. Win32-Version: 4.6.1080.0 built by: NETFXREL3STAGE.
CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll.

DSCM Assembly-Version: 1.0.5983.37891. Win32-Version: 1.0.5983.37891.
CodeBase: file:///D:/Eigene%20Dateien/Desktop/DSCM.exe.
```

**Comment by Chronial** [comment]
Also reported [by atikuss on Reddit](https://www.reddit.com/r/darksouls/comments/4ilq2x/dscm_dark_souls_connectivity_mod/d3h3nlh):
```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
at DSCM.DarkSoulsProcess.findDllAddresses() at DSCM.DarkSoulsProcess..ctor()
at DSCM.MainWindow.attachDSProcess()
at DSCM.MainWindow.Lambda$_R19-5(Object a0, EventArgs a1)
at System.Windows.Forms.Timer.OnTick(EventArgs e)
at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib Assembly Version: 4.0.0.0 Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

DSCM Assembly Version: 1.0.5983.37891 Win32 Version: 1.0.5983.37891
CodeBase: file:///C:/Users/PC/Desktop/DSCM.exe```

**Comment by Chronial** [comment]
@Wulf2k I unfortunately have no idea what exactly you released, as you didn't push the version you released.

**Comment by Chronial** [comment]
These are the relevant changes since the last version:
https://github.com/Wulf2k/DaS-PC-MPChan/compare/b0ec025...master#diff-1077b06ccf265332b8a199824faad952L122
and maybe
https://github.com/Wulf2k/DaS-PC-MPChan/compare/b0ec025...master#diff-1077b06ccf265332b8a199824faad952R99

**Comment by Chronial** [comment]
And there we go. Next time I should probably read [the docs](https://msdn.microsoft.com/en-us/library/system.diagnostics.fileversioninfo.productname%28v=vs.110%29.aspx) properly. But well, their example contains the same error ^^.

So what happened? People replaced their `d3d9.dll` with one that is neither the default nor pvp watchdog. And their `d3d9.dll` does not contain version information, so `ProductName` is `Nothing`. Calling `.Contains()` on that throws the exception.

**Comment by Chronial** [comment]
@Wulf2k This kind of analysis would be a little bit easier if you would tag the releases in git. You can do that like this:

1. Commit the state of the code you are going to release
2. Tag the current commit by running `git tag v**VERSION**` – e.g. `git tag v2016-05-12-22`
3. Push the newly created tag by running `git push --tags`

**Comment by Wulf2k** [comment]
First attempt at using tags, how's that looking?

**Comment by Chronial** [comment]
Good :) https://github.com/Wulf2k/DaS-PC-MPChan/tree/2016-05-24-20

But now we disagreed on the format of the tags (with `v` vs without): ![screenshot](http://chronial.de/misc/screenshots/firefox_2016-05-25_12-11-13.png)

I would recommend starting with `v`, it makes it easier to see which name in git is a version tag. But your call. Make a decision and then ideally change the other tag. If you go for with `v`:

```
git tag v2016-05-24-20 2016-05-24-20
git tag -d 2016-05-24-20
git push origin --tags :refs/tags/2016-05-24-20
```

If you go without `v`:

```
git tag 2016-05-12-22 v2016-05-12-22
git tag -d v2016-05-12-22
git push origin --tags :refs/tags/v2016-05-12-22
```

**Comment by Wulf2k** [comment]
Hrm.

fatal: Failed to resolve '2016-05-24-20' as a valid ref.

**Comment by Chronial** [comment]
Which command did that happen on?
I changed the tag on the server to include `v` for now. If you now remove your local version without `v` (`git tag -d 2016-05-24-20`), you should be fine.
