### ISSUE TITLE
[Question] Patch steam

### ISSUE THREAD

**Issue by gpotter2** [Wulf2k/DaS-PC-MPChan#87]
I'm asking myself if it is DSCM's role to also patch the old DarkSouls steam bugs.... For instance, when you are loading the game, you'll get the setup thing which will try to install GFWL for a sec. That can be removed by launching something like this as administrator:
```
Private Sub patchSteam()
        Try
            If Environment.Is64BitOperatingSystem Then
                My.Computer.Registry.LocalMachine.OpenSubKey("Software\Wow6432Node\Valve\Steam\Apps\211420").SetValue("gfwlivesetup", 1)
            Else
                My.Computer.Registry.LocalMachine.OpenSubKey("Software\Valve\Steam\Apps\211420").SetValue("gfwlivesetup", 1)
            End If
        Catch ex As UnauthorizedAccessException
        End Try
    End Sub
```

Which make steam feels like it's already installed...

But should DSCM do that ?

**Comment by Wulf2k** [comment]
Eh, it doesn't really fit into the realm of what DSCM should be doing.  It's handy, sure, but I think that's more something that should be posted in the forums than rolled into DSCM.

Especially since it needs administrator rights.

**Comment by gpotter2** [comment]
I though that too
Thanks for your answer :)
