### ISSUE TITLE
[Nexus] DSCM Update

### ISSUE THREAD

**Issue by julien-ramsamy** [Wulf2k/DaS-PC-MPChan#93]
Greetings,

As far you defined a new stable version with the <2016-05-24-20>,
Please consider updating your [page](http://www.nexusmods.com/darksouls/mods/1047/?) on NexusMod,
It remains a great vector to spread mod/tool. :)

@Wulf2k & @Chronial,
Thank you for yours spare times spent on this project.

Kind Regards.

**Comment by Wulf2k** [comment]
Illusorywall was originally the maintainer on the Nexus.  I'll contact him to see if he can update it there.

**Comment by Chronial** [comment]
Any news on this? I think a lot of people will go to nexus even after reading about the mod somewhere else, because nexus is trusted and it's way less likely to get a virus from nexus than a random internet page.

**Comment by Wulf2k** [comment]
Updated on Nexus.
