### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Chronial** [Wulf2k/DaS-PC-MPChan#97]
The program crashes on startup for some users. Error message is "... stopped working".

Reports:
http://steamcommunity.com/app/211420/discussions/0/364042703864810164/

https://www.reddit.com/r/darksouls/comments/4ilq2x/dscm_dark_souls_connectivity_mod/d3nslny

**Comment by Chronial** [comment]
https://www.reddit.com/r/darksouls/comments/4lil96/daspcmpchan_has_stopped_working/

**Comment by Chronial** [comment]
Gave ZiggyTheLegend a version without autoattach, still crashes.

**Comment by Wulf2k** [comment]
Weird.

Is it irc then somehow?

**Comment by Chronial** [comment]
I will try to check

**Comment by Wulf2k** [comment]
I'll have the kids in bed within the hour and I'll take a closer look as
well.

**Comment by Chronial** [comment]
Found the problem: They are using an old version of .net (4.0), but DSCM requires 4.5. As you did not actually use any 4.5 features in the previous stable, that did run on 4.0. But I used quite a few 4.5 features, so that doesn't work anymore. And apparently .net is not smart enough to register this and just crashes instead …

So there's two things we can do:
1. Tell people to get the current .net version from https://www.microsoft.com/en-us/download/confirmation.aspx?id=42643 and make it clear that DSCM needs 4.5 (which is preinstalled since windows 8) or
2. Remove all 4.5 features and target 4.0. That will be quite annoying since the auto-updater uses a lot of 4.5 (Async and the zip module).

What do you think?

**Comment by Wulf2k** [comment]
I'm fine with 4.5 being required.

**Comment by Chronial** [comment]
Then that should be stated on

* Your hompage
* The reddit thread and every release announcement
* The nexus page
* The readme

**Comment by Chronial** [comment]
Doesn't look like we got more reports for this, so I guess it's fix. Leaving this open till the nexus page contains a note about 4.5.

**Comment by Picuritcha** [comment]
I'm not sure if I should even be here, but I'm getting this error on Windows 10, updated .net
I'm not sure which part of the error log I should post (or even IF I should post), but it does seem to be somewhat related to .net framework from the little I could get.

**Comment by Wulf2k** [comment]
Nexus does note that 4.5 is required.
